### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by GordPavel** [ilya-sayenko/java-zoom-aggregator#1]
# Привет)
Очень хорошая работа, мне понравилось. Что хотелось бы улучшить:
1. https://github.com/ilya-sayenko/java-zoom-aggregator/blob/33ce7eb21359ccbc70a85466affa9a0c342d6eea/src/main/java/Report.java#L45-L50 тебе не зачем получать список конференций. В входных данных гарантированно на 1 файл – одна конфа. Но в некоторых системах (к примеру Macos ) в папках всегда есть лишние скрытые файлы. Так что, если в файле не получилось распарсить конференцию, то лучше пропускать данный файл. Можешь воспользоваться классом `Optional`
2. https://github.com/ilya-sayenko/java-zoom-aggregator/blob/33ce7eb21359ccbc70a85466affa9a0c342d6eea/src/main/java/Report.java#L43 лучше сделать, чтобы метод возвращал объект, а не пихал в коллекцию. лучше на уровень выше класть в коллекцию. И сделать его private
3. https://github.com/ilya-sayenko/java-zoom-aggregator/blob/33ce7eb21359ccbc70a85466affa9a0c342d6eea/src/main/java/Report.java#L108 нет необходимости генерить строку в память и потом писать в std out. Лучше сразу писать в вывод – меньше памяти потратишь
4. https://github.com/ilya-sayenko/java-zoom-aggregator/blob/33ce7eb21359ccbc70a85466affa9a0c342d6eea/src/main/java/Report.java#L65 метод объединен с вычислением статистики. Для лучшей читаемости кода лучше вынести вычисление статистики по всем в отдельный метод и в `Main` явно вызывать. Тогда в Main довольно очевидно будет выглядеть 
```java
Report report = new Report();
report.readParticipants(partsPath);
report.readConferences(repsPath);
report.calculateStatistics();
report.printReport(new BufferedWriter(new OutputStreamWriter(System.out)));
```
5. https://github.com/ilya-sayenko/java-zoom-aggregator/blob/33ce7eb21359ccbc70a85466affa9a0c342d6eea/src/main/java/Main.java#L6-L18
Можно идти по массиву опций и элементы на нечетных индексах сделать ключами, на четных – значениями мапы. И назвать такой метод в `Main.parseArguments`. Потом уже передавать аргументы дальше по коду
6. Чисто улучшения итогового файла:
a. Разделить `id конфы – время начала` на разные строки. Так проще потом сортировать по датам
b. Разделить `кол-во участников – процент участников` на разные строки
c. Разделить `кол-во посещенных вебинаров – средний процент просещения` на разные столбцы
d. Перенести разделенные столбцы `кол-во посещенных вебинаров – средний процент просещения` влево к имени и почте
e. На строке с `id конференции` над именем, почтой и тд до колонок с id конференций добавить называния столбцов
f. В колонке с именем гостя добавить названия строк

**Comment by GordPavel** [comment]
7. Почитай, как с помощью мавен собрать jar со всеми зависимостями. Можно прям в поисковике `maven executable jar`

**Comment by ilya-sayenko** [comment]
@GordPavel Я правильно понял, что итоговый файл должен быть примерно таким?
[responce.csv](https://github.com/ilya-sayenko/java-zoom-aggregator/files/10732799/responce.csv)

**Comment by GordPavel** [comment]
Да, все верно)

**Comment by ilya-sayenko** [comment]
@GordPavel Спасибо за фидбек. Замечания поправил.
